### ISSUE TITLE
Possible misspelling "ResetOrhpans"

### ISSUE THREAD

**Issue by AndrewADev** [NomadeonSoftwareLLC/LiteQueue#1]
I'm assuming that this method: 
https://github.com/NomadeonSoftwareLLC/LiteQueue/blob/f0a51d57564e1d48823937515fddef8ce368da77/src/LiteQueue/LiteQueue.cs#L165

Likely intends to be called `ResetOrphans`. Would that be correct?

**Comment by nbushby** [comment]
Correct, committed a fix. Also noticed the method above, CurrentCheckouts, had a copy and paste error in the exception text. Changed the method name strings to nameof(x) usage for future refactoring integrity.

**Comment by nbushby** [comment]
Released into 1.0.1 in nuget
https://www.nuget.org/packages/LiteQueue/1.0.1
