### ISSUE TITLE
typo in readme.md

### ISSUE THREAD

**Issue by kondelik** [NomadeonSoftwareLLC/LiteQueue#4]
Hi,
you have typo in [readme.md](https://github.com/NomadeonSoftwareLLC/LiteQueue/blob/master/README.md)

`logs.ResetOrhpans();` should be `logs.ResetOrphans();` (its not clearly visible, but two letters (H and P) are swapped in "Orphans")

**Comment by kondelik** [comment]
oh, lol, its  #1 but in example.

**Comment by nbushby** [comment]
Thanks for submitting, fixed.
