### ISSUE TITLE
LiteDB v5 compatibility

### ISSUE THREAD

**Issue by kutsoff** [NomadeonSoftwareLLC/LiteQueue#6]
Hello,

Could you provide info about NuGET package for LiteDB v5? Current 1.1.0 version doesn't works with LiteDB 5

**Comment by nbushby** [comment]
Unit tests (specifically those within LiteQueueTest_Threaded) are failing with LiteDB 5. Have not yet determined cause. Example:

 Single
   Source: LiteQueueTest_Threaded.cs line 54
   Duration: 824 ms

  Message: 
    Test method LiteQueueTests.LiteQueueTest_Threaded.Single threw exception: 
    LiteDB.LiteException: Invalid Collection on 0. Full zero: True. Page Type: Empty. Prev/Next: 0/0. UniqueID: 5. ShareCounter: 1. 
  Stack Trace: 
    LiteQueueTest_Threaded.RunTasks(Action producer, Action consumer, Int32 producerCount, Int32 consumerCount) line 142
    LiteQueueTest_Threaded.Single() line 60

**Comment by kutsoff** [comment]
I see. Thanks for reply
